name: git-hub-action-pipeline
on:
  workflow_dispatch:
jobs:
  job1:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      
      - name: Run a one-line script
        run: echo Hello, world!


      - name: az login
        run: az login --service-principal --username 55b808d7-84a3-4b34-b6ef-30aed45e3dfa --password Urz8Q~vr2Zh_0xoqHRuANQwIlDZQkRBEt.x5hdAg --tenant d9e397f1-a75f-4aef-8870-84abaee8c5ec
